# Smack loads providers and Android initialization metadata by class name.
-keep class org.jivesoftware.smack.** { *; }
-keep class org.jivesoftware.smackx.** { *; }
-keep class org.jxmpp.** { *; }
-keepattributes Signature,*Annotation*

# libsignal's Curve25519 facade constructs its provider by its original class name.
# Without this rule R8 renames or removes the provider in release builds, so OMEMO
# fails while generating the account's first identity key.
-keep class org.whispersystems.curve25519.** { *; }

# libsignal 2.x protocol messages are generated by protobuf 2.x. Its runtime
# builds accessor method names dynamically (for example, getRatchetKey), so R8
# cannot discover those reflective calls by static analysis.
-keep class org.whispersystems.libsignal.**Protos { *; }
-keep class org.whispersystems.libsignal.**Protos$* { *; }

# Room's generated implementations are referenced by naming convention.
-keep class * extends androidx.room.RoomDatabase
