# Smack loads core providers and Android initialization metadata by class name.
-keep class org.jivesoftware.smack.** { *; }
-keep class org.jxmpp.** { *; }
-keepattributes Signature,*Annotation*

# Extension initializers and stanza providers are listed in Smack's metadata and instantiated by
# class name. Preserve those entry points without retaining every optional smack-extensions feature
# (notably OpenPGP and its desktop Bouncy Castle provider) in the Android APK.
-keep class * implements org.jivesoftware.smack.initializer.SmackInitializer { *; }
-keep class * extends org.jivesoftware.smack.provider.IqProvider { *; }
-keep class * extends org.jivesoftware.smack.provider.ExtensionElementProvider { *; }

# smack-omemo/omemo.xml loads this class by its literal name during Smack startup.
-keep,allowoptimization class org.jivesoftware.smackx.omemo.OmemoManager

# XmppElementUtil reads these public constants by their literal field names. Keep the fields while
# still allowing R8 to optimize and remove extension implementations Jarboa never uses.
-keepclassmembers class * implements org.jivesoftware.smack.packet.NamedElement {
    public static final java.lang.String ELEMENT;
}
-keepclassmembers class * implements org.jivesoftware.smack.packet.FullyQualifiedElement {
    public static final java.lang.String NAMESPACE;
}

# libsignal's Curve25519 facade constructs its provider by its original class name.
# Without this rule R8 renames or removes the provider in release builds, so OMEMO
# fails while generating the account's first identity key.
-keep class org.whispersystems.curve25519.** { *; }

# libsignal 2.x protocol messages are generated by protobuf 2.x. Its runtime
# builds accessor method names dynamically (for example, getRatchetKey), so R8
# cannot discover those reflective calls by static analysis.
-keep class org.whispersystems.libsignal.**Protos { *; }
-keep class org.whispersystems.libsignal.**Protos$* { *; }

# Room's generated implementations are referenced by naming convention.
-keep class * extends androidx.room.RoomDatabase
